# Generated by Django 5.1.4 on 2025-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0003_remove_watchlater_video_id_watchlater_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlater',
            name='song',
        ),
        migrations.AddField(
            model_name='watchlater',
            name='video_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
