# Generated by Django 5.1.4 on 2025-03-25 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0002_song_credit_watchlater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlater',
            name='video_id',
        ),
        migrations.AddField(
            model_name='watchlater',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicbeats.song'),
        ),
    ]
